// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0qOd4OA_AbA1zPeSU2Qyuokl4O5gFsU',
    appId: '1:48884043512:web:d8982b50616030b81c750d',
    messagingSenderId: '48884043512',
    projectId: 'my-chat-prj-firebase',
    authDomain: 'my-chat-prj-firebase.firebaseapp.com',
    storageBucket: 'my-chat-prj-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGauyCZ_qa6Rr18gNItdDMX9hKDFVZl9w',
    appId: '1:48884043512:android:3ee616208c4708f51c750d',
    messagingSenderId: '48884043512',
    projectId: 'my-chat-prj-firebase',
    storageBucket: 'my-chat-prj-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Sp62FggC1KczzRUsA-2xxaCm84JDvE8',
    appId: '1:48884043512:ios:a5d3192a455070d81c750d',
    messagingSenderId: '48884043512',
    projectId: 'my-chat-prj-firebase',
    storageBucket: 'my-chat-prj-firebase.appspot.com',
    iosClientId: '48884043512-311neb9n1h3q98b9ud3f8etnamtbudg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Sp62FggC1KczzRUsA-2xxaCm84JDvE8',
    appId: '1:48884043512:ios:a5d3192a455070d81c750d',
    messagingSenderId: '48884043512',
    projectId: 'my-chat-prj-firebase',
    storageBucket: 'my-chat-prj-firebase.appspot.com',
    iosClientId: '48884043512-311neb9n1h3q98b9ud3f8etnamtbudg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatAppFirebase',
  );
}
